// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20260930115308_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.Property<int>("Block_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Block_id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PrisonId")
                        .HasColumnType("int");

                    b.Property<int>("Security_level")
                        .HasColumnType("int");

                    b.HasKey("Block_id");

                    b.HasIndex("PrisonId");

                    b.ToTable("Block");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<int>("Prison_id")
                        .HasColumnType("int");

                    b.HasKey("BuildingId");

                    b.HasIndex("Prison_id");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Chamber", b =>
                {
                    b.Property<int>("chamberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chamberId"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("Maximum_capacity")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("chamberId");

                    b.HasIndex("BlockId");

                    b.ToTable("Chamber");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Crime", b =>
                {
                    b.Property<int>("CrimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrimeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Difficulty_level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CrimeId");

                    b.ToTable("Crime");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Guards", b =>
                {
                    b.Property<int>("GuardsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuardsId"));

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PrisonId")
                        .HasColumnType("int");

                    b.Property<int>("Worker_Number")
                        .HasColumnType("int");

                    b.Property<string>("job")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("GuardsId");

                    b.HasIndex("PrisonId");

                    b.ToTable("Guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prison", b =>
                {
                    b.Property<int>("PrisonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrisonId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Maximum_capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PrisonId");

                    b.ToTable("Prisons");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prisoners", b =>
                {
                    b.Property<int>("PrisonerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrisonerId"));

                    b.Property<DateTime>("Arrival_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChamberId")
                        .HasColumnType("int");

                    b.Property<int>("CrimeId")
                        .HasColumnType("int");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Personal_Number")
                        .HasColumnType("int");

                    b.Property<bool>("Prisoner_Status")
                        .HasColumnType("bit");

                    b.Property<int>("PunishmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dob")
                        .HasColumnType("datetime2");

                    b.HasKey("PrisonerId");

                    b.HasIndex("ChamberId");

                    b.HasIndex("CrimeId");

                    b.HasIndex("PunishmentId");

                    b.ToTable("Prisoners");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Punishment", b =>
                {
                    b.Property<int>("PunishmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PunishmentId"));

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Punishment_Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("PunishmentId");

                    b.ToTable("Punishment");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finish_Time")
                        .HasColumnType("int");

                    b.Property<int>("GuardsId")
                        .HasColumnType("int");

                    b.Property<int>("Start_Time")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.HasIndex("GuardsId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finish_Time")
                        .HasColumnType("int");

                    b.Property<int>("GuardsId")
                        .HasColumnType("int");

                    b.Property<int>("PrisonerId")
                        .HasColumnType("int");

                    b.Property<int>("Start_Time")
                        .HasColumnType("int");

                    b.Property<string>("Visiting_Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("VisitId");

                    b.HasIndex("GuardsId");

                    b.HasIndex("PrisonerId");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visitors", b =>
                {
                    b.Property<int>("VisitorsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorsId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personal_Number")
                        .HasColumnType("int");

                    b.Property<string>("Relation_To_Prisoner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorsId");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Blocks")
                        .HasForeignKey("PrisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Building", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Buildings")
                        .HasForeignKey("Prison_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Chamber", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Block", "Block")
                        .WithMany("Chambers")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Guards", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Guards")
                        .HasForeignKey("PrisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prisoners", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Chamber", "Chamber")
                        .WithMany("Prisoners")
                        .HasForeignKey("ChamberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Crime", "Crime")
                        .WithMany("Prisoners")
                        .HasForeignKey("CrimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Punishment", "Punishment")
                        .WithMany("Prisoners")
                        .HasForeignKey("PunishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamber");

                    b.Navigation("Crime");

                    b.Navigation("Punishment");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shift", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Guards", "Guards")
                        .WithMany("Shifts")
                        .HasForeignKey("GuardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visit", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Guards", "Guards")
                        .WithMany("Visits")
                        .HasForeignKey("GuardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Prisoners", "Prisoner")
                        .WithMany("Visits")
                        .HasForeignKey("PrisonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guards");

                    b.Navigation("Prisoner");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.Navigation("Chambers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Chamber", b =>
                {
                    b.Navigation("Prisoners");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Crime", b =>
                {
                    b.Navigation("Prisoners");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Guards", b =>
                {
                    b.Navigation("Shifts");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prison", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Buildings");

                    b.Navigation("Guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prisoners", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Punishment", b =>
                {
                    b.Navigation("Prisoners");
                });
#pragma warning restore 612, 618
        }
    }
}
