// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    partial class DatabaseTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PrisonId")
                        .HasColumnType("int");

                    b.Property<int>("Security_Level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrisonId");

                    b.ToTable("Block");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PrisonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrisonId");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Chamber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("Maxiumum_Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("Chamber");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Crime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Difficulty_Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Crime");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Guards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PrisonId")
                        .HasColumnType("int");

                    b.Property<int>("Worker_Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrisonId");

                    b.ToTable("Guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Maxiumum_Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prisoners", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Arrival_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChamberId")
                        .HasColumnType("int");

                    b.Property<int>("CrimeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Personal_Number")
                        .HasColumnType("int");

                    b.Property<bool>("Prisoner_Status")
                        .HasColumnType("bit");

                    b.Property<int>("PunishmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChamberId");

                    b.HasIndex("CrimeId");

                    b.HasIndex("PunishmentId");

                    b.ToTable("Prisoners");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Punishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Punishment_Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Punishment");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finish_time")
                        .HasColumnType("int");

                    b.Property<int>("GuardsId")
                        .HasColumnType("int");

                    b.Property<int>("Start_time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuardsId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Finish_Time")
                        .HasColumnType("int");

                    b.Property<int>("PrisonersId")
                        .HasColumnType("int");

                    b.Property<int>("Start_Time")
                        .HasColumnType("int");

                    b.Property<string>("Visiting_Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("VisitorsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrisonersId");

                    b.HasIndex("VisitorsId");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visitors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Personal_Number")
                        .HasColumnType("int");

                    b.Property<string>("Relation_To_The_Prisoner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telphone_Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Block", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Block")
                        .HasForeignKey("PrisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Building", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Building")
                        .HasForeignKey("PrisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Chamber", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Guards", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prison", "Prison")
                        .WithMany("Guards")
                        .HasForeignKey("PrisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prison");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prisoners", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Chamber", "Chamber")
                        .WithMany()
                        .HasForeignKey("ChamberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Crime", "Crime")
                        .WithMany()
                        .HasForeignKey("CrimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Punishment", "Punishment")
                        .WithMany()
                        .HasForeignKey("PunishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamber");

                    b.Navigation("Crime");

                    b.Navigation("Punishment");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Shift", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Guards", "Guards")
                        .WithMany()
                        .HasForeignKey("GuardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Visit", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Prisoners", "Prisoners")
                        .WithMany()
                        .HasForeignKey("PrisonersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Visitors", "Visitors")
                        .WithMany()
                        .HasForeignKey("VisitorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prisoners");

                    b.Navigation("Visitors");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Prison", b =>
                {
                    b.Navigation("Block");

                    b.Navigation("Building");

                    b.Navigation("Guards");
                });
#pragma warning restore 612, 618
        }
    }
}
