// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    partial class DatabaseTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Lend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LahteLennujaamId")
                        .HasColumnType("int");

                    b.Property<int>("LennuFirmaId")
                        .HasColumnType("int");

                    b.Property<int>("LennukId")
                        .HasColumnType("int");

                    b.Property<string>("Lennunumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SaabumiseKuupaevJaAeg")
                        .HasColumnType("datetime2");

                    b.Property<int>("SihtLennujaamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValjumiseKuupaevJaAeg")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaravId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LahteLennujaamId");

                    b.HasIndex("LennuFirmaId");

                    b.HasIndex("LennukId");

                    b.HasIndex("SihtLennujaamId");

                    b.HasIndex("VaravId");

                    b.ToTable("Lend");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.LennuFirma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Riik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LennuFirma");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.LennuStaatuseAjalugu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LendId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MuutmiseAeg")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pohjus")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Staatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LendId");

                    b.ToTable("LennuStaatuseAjalugu");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Lennujaam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Linn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Riik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Lennujaam");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Lennuk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsteKohtadeArv")
                        .HasColumnType("int");

                    b.Property<string>("Mudel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Registreerimisnumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ValmistamiseAasta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lennuk");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Pagas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kaal")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PagasiTuup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PagasilipikuNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RegistreerimiseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistreerimiseId");

                    b.ToTable("Pagas");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Registreerimine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IsteKohaNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LendId")
                        .HasColumnType("int");

                    b.Property<string>("PiletiTuup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegistreerimiseAeg")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReisijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LendId");

                    b.HasIndex("ReisijaId");

                    b.ToTable("Registreerimine");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Reisija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DokumendiNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Sunniaeg")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Reisija");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asukoht")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nimetus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TerminaliNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Terminal");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Töötaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ametikoht")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TerminalId")
                        .HasColumnType("int");

                    b.Property<string>("TöötajaNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("Töötaja");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Varav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asukoht")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaxLennukiSuurus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TerminalId")
                        .HasColumnType("int");

                    b.Property<int>("VaravaNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("Varav");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Lend", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Lennujaam", "LahteLennujaam")
                        .WithMany("LahteLennud")
                        .HasForeignKey("LahteLennujaamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.LennuFirma", "LennuFirma")
                        .WithMany("Lennud")
                        .HasForeignKey("LennuFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Lennuk", "Lennuk")
                        .WithMany("Lennud")
                        .HasForeignKey("LennukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Lennujaam", "SihtLennujaam")
                        .WithMany("SihtLennud")
                        .HasForeignKey("SihtLennujaamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Varav", "Varav")
                        .WithMany("Lennud")
                        .HasForeignKey("VaravId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LahteLennujaam");

                    b.Navigation("LennuFirma");

                    b.Navigation("Lennuk");

                    b.Navigation("SihtLennujaam");

                    b.Navigation("Varav");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.LennuStaatuseAjalugu", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Lend", "Lend")
                        .WithMany("StaatuseAjalugu")
                        .HasForeignKey("LendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lend");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Pagas", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Registreerimine", "Registreerimine")
                        .WithMany("Pagasid")
                        .HasForeignKey("RegistreerimiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registreerimine");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Registreerimine", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Lend", "Lend")
                        .WithMany("Registreerimised")
                        .HasForeignKey("LendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.Reisija", "Reisija")
                        .WithMany("Registreerimised")
                        .HasForeignKey("ReisijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lend");

                    b.Navigation("Reisija");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Töötaja", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Terminal", "Terminal")
                        .WithMany("Töötajad")
                        .HasForeignKey("TerminalId");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Varav", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Terminal", "Terminal")
                        .WithMany("Varavad")
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Lend", b =>
                {
                    b.Navigation("Registreerimised");

                    b.Navigation("StaatuseAjalugu");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.LennuFirma", b =>
                {
                    b.Navigation("Lennud");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Lennujaam", b =>
                {
                    b.Navigation("LahteLennud");

                    b.Navigation("SihtLennud");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Lennuk", b =>
                {
                    b.Navigation("Lennud");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Registreerimine", b =>
                {
                    b.Navigation("Pagasid");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Reisija", b =>
                {
                    b.Navigation("Registreerimised");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Terminal", b =>
                {
                    b.Navigation("Töötajad");

                    b.Navigation("Varavad");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Varav", b =>
                {
                    b.Navigation("Lennud");
                });
#pragma warning restore 612, 618
        }
    }
}
